apiVersion: batch/v1
kind: Job
metadata: 
  name:  {{ include "livegrep.jobName" .}}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
  labels:
    {{- include "livegrep.labels" . | nindent 4 }}
spec:
  template:
    spec:
      {{- with .Values.job.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: cleanup-repos
          image: busybox
          command: ["sh", "-c"]
          args: ["rm -rf /data/* /data/.* || true"]
          volumeMounts:
            - name: index-volume
              mountPath: /data
      containers:
        - name: indexer
          image: "{{ .Values.job.image.repository }}:{{ .Values.job.image.tag | default .Chart.AppVersion }}"
          command: ["/livegrep/bin/livegrep-github-reindex"]
          args:
            - "-http"
            {{- range .Values.job.repos }}
            - "-repo"
            - "{{ . }}"
            {{- end }}
            {{- range .Values.job.users }}
            - "-user"
            - "{{ . }}"
            {{- end }}
            - "-out"
            - "/data/livegrep.idx"
            - "-dir"
            - "/data"
          volumeMounts:
            - name: index-volume
              mountPath: /data
          env:
            {{- toYaml .Values.job.env | nindent 12 }}
      restartPolicy: Never
      volumes:
        - name: index-volume
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}