apiVersion: v1
kind: Service
metadata:
  name: {{ include "livegrep.frontendName" . }}
  labels:
    component: frontend
    {{- include "livegrep.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }} 
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http 
  selector:
    {{- include "livegrep.selectorLabels" . | nindent 4 }}
