{{- if .Values.pvc.create -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }} 
  labels:
    {{- include "livegrep.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.size }} 
  storageClassName: {{ .Values.pvc.storageClassName }} 
{{- end }}

