nameOverride: ""
fullnameOverride: ""

job:
  repos:
    - livegrep/livegrep
  users:
    - nginx
  image:
    repository: ghcr.io/livegrep/livegrep/indexer
    pullPolicy: IfNotPresent
    tag: "latest"
  imagePullSecrets: []
  env:
    []
    # - name: GITHUB_KEY
    #   valueFrom:
    #     secretKeyRef:
    #       name: livegrep-github-token
    #       key: github-token

pvc:
  create: true
  name: livegrep-pvc
  size: 2Gi
  # storageClassName: standard

backend:
  image:
    repository: ghcr.io/livegrep/livegrep/base
    pullPolicy: IfNotPresent
    tag: "latest"
  imagePullSecrets: []
  replicaCount: 1
  podAnnotations: {}
  podLabels: {}
  service:
    type: ClusterIP
    port: 9999

frontend:
  image:
    repository: ghcr.io/livegrep/livegrep/base
    pullPolicy: IfNotPresent
    tag: "latest"
  imagePullSecrets: []
  replicaCount: 1
  podAnnotations: {}
  podLabels: {}
  service:
    type: ClusterIP
    port: 8910
